<?php echo $this->getMessagesBlock()->getGroupedHtml(); 
$config = $this->getSession('Config');
?>
<div class="returnContainer">
    <div class="registered-users">
        <div class="page-title"><h1><?php echo $this->translate('LoginOrder');?></h1></div>
        <p><?php echo $this->translate('LoginOrderText');?></p>
        <br /><br />
        <form action="" method="post">
            <table cellpadding="0" cellspacing="0" border="0" width="100%">
                <tr>
                    <td width="25%">
                        <fieldset>
                            <table cellpadding="0" cellspacing="0" border="0" width="100%">
                                <tr>
                                    <td width="51%"><label for"ordernumber"><?php echo $this->translate('orderNummer');?></label></td>
                                    <td><input type="text" name="ordernumber" id="ordernumber" /></td>
                                </tr>
                                <tr><td colspan="2" align="right"> &nbsp;</td></tr>
                                <tr>
                                    <td><label for"postcode"><?php echo $this->translate('postcode');?></label></td>
                                    <td><input type="text" name="postcode" id="postcode" /></td>
                                </tr>
                                <tr><td colspan="2" align="right"> &nbsp;</td></tr>
                                <tr align="right">
                                    <td colspan="1" align="left"><div class="buttons buttons-set"><button onclick="history.back()" class="returnBtnBig btn btn-cart add-to-cart button" type="button"  /><span><span><?php echo $this->translate('Terug')?></span></span></button></div></td>
                                    <td colspan="1" align="right"><div class="buttons buttons-set"><button class="returnBtnBig btn btn-cart add-to-cart button" type="submit"  /><span><span><?php echo $this->translate('LoginOrder')?></span></span></button></div></td></tr>
                           </table>
                        </fieldset>
                    </td>
                    <td width="50%">
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>